import java.util.Arrays;
import java.util.LinkedList;

public class ListUrl {

	
	public LinkedList<String> getListUrl(){
		String[] sa = new String[] {
				
				"https://www.opentable.com/lobster-bar-sea-grille"
				/*
				"https://www.opentable.com/r/rivertail-fort-lauderdale",
				"https://www.opentable.com/r/casa-sensei-for-lauderdale",
				"https://www.opentable.com/r/pla-at-seminole-hard-rock-fort-lauderdale",
				"https://www.opentable.com/r/jonny-nobones-at-the-old-river-house-fort-lauderdale",
				"https://www.opentable.com/boatyard",
				"https://www.opentable.com/r/louie-bossis-ristorante-fort-lauderdale",
				"https://www.opentable.com/r/yot-bar-and-kitchen-fort-lauderdale",
				"https://www.opentable.com/yolo",
				"https://www.opentable.com/serafina-by-the-water",
				"https://www.opentable.com/chima-brazilian-steakhouse-fort-lauderdale",
				"https://www.opentable.com/bistro-mezzaluna",
				"https://www.opentable.com/r/andys-live-fire-grill-fort-lauderdale",
				"https://www.opentable.com/the-capital-grille-ft-lauderdale",
				"https://www.opentable.com/r/doc-bs-restaurant-and-bar-fort-lauderdale",
				"https://www.opentable.com/r/bar-rita-fort-lauderdale-2",
				"https://www.opentable.com/steak-954-at-the-w-fort-lauderdale",
				"https://www.opentable.com/r/big-city-tavern-las-olas-fort-lauderdale",
				"https://www.opentable.com/casa-d-angelo",
				"https://www.opentable.com/r/lona-cocina-tequileria-fort-lauderdale",
				"https://www.opentable.com/shooters-waterfront",
				"https://www.opentable.com/s3-restaurant",
				"https://www.opentable.com/r/tap-42-fort-lauderdale",
				"https://www.opentable.com/r/mortons-the-steakhouse-ft-lauderdale-fort-lauderdale",
				"https://www.opentable.com/burlock-coast",
				"https://www.opentable.com/r/b-square-ft-lauderdale",
				"https://www.opentable.com/cafe-vico-ristorante",
				"https://www.opentable.com/r/luigis-tuscan-grill-fort-lauderdale",
				"https://www.opentable.com/r/mastros-ocean-club-fort-lauderdale",
				"https://www.opentable.com/r/sparrow-fort-lauderdale",
				"https://www.opentable.com/r/wild-thyme-fort-lauderdale",
				"https://www.opentable.com/seasons-52-fort-lauderdale",
				"https://www.opentable.com/ruths-chris-steak-house-fort-lauderdale",
				"https://www.opentable.com/r/blue-moon-fish-co-fort-lauderdale",
				"https://www.opentable.com/r/pizza-craft-ft-lauderdale",
				"https://www.opentable.com/r/gatsbys-joint-fort-lauderdale-2",
				"https://www.opentable.com/r/thasos-island-fort-lauderdale",
				"https://www.opentable.com/r/coopers-hawk-winery-and-restaurant-coconut-creek",
				"https://www.opentable.com/r/dune-at-auberge-beach-fort-lauderdale",
				"https://www.opentable.com/r/cubanos-by-mario-fort-lauderdale",
				"https://www.opentable.com/r/3030-ocean-fort-lauderdale",
				"https://www.opentable.com/r/the-wilder-fort-lauderdale",
				"https://www.opentable.com/sky-thai-sushi",
				"https://www.opentable.com/r/padrinos-cuban-cuisine-boca-raton",
				"https://www.opentable.com/r/el-vez-ft-lauderdale-fort-lauderdale",
				"https://www.opentable.com/benihana-fort-lauderdale",
				"https://www.opentable.com/r/wine-and-garden-fort-lauderdale",
				"https://www.opentable.com/r/casa-calabria-fort-lauderdale",
				"https://www.opentable.com/spazio-fort-lauderdale",
				"https://www.opentable.com/r/cafe-ibiza-fort-lauderdale",
				"https://www.opentable.com/r/harborwood-and-harborwood-bar-hyatt-centric-hotel-fort-lauderdale",
				"https://www.opentable.com/r/15th-street-fisheries-fort-lauderdale",
				"https://www.opentable.com/r/gastrotheque-fort-lauderdale",
				"https://www.opentable.com/r/hardy-park-bistro-fort-lauderdale",
				"https://www.opentable.com/r/frenchys-table-lauderdale-by-the-sea",
				"https://www.opentable.com/r/moksha-indian-brasserie-fort-lauderdale",
				"https://www.opentable.com/sette-bello-fort-lauderdale",
				"https://www.opentable.com/r/dal-contadino-trattoria-fort-lauderdale",
				"https://www.opentable.com/r/eatapas-fort-lauderdale",
				"https://www.opentable.com/r/da-livio-fort-lauderdale",
				"https://www.opentable.com/r/anthonys-clam-house-fort-lauderdale",
				"https://www.opentable.com/r/red-lobster-fort-lauderdale",
				"https://www.opentable.com/r/lips-fort-lauderdale-oakland-park",
				"https://www.opentable.com/wild-sea-oyster-bar-and-grille",
				"https://www.opentable.com/r/american-social-club-fort-lauderdale",
				"https://www.opentable.com/cafe-martorano-fort-lauderdale",
				"https://www.opentable.com/sea-level",
				"https://www.opentable.com/r/even-keel-fish-and-oyster-fort-lauderdale",
				"https://www.opentable.com/r/candela-restaurant-wine-bar-tapas-fort-lauderdale",
				"https://www.opentable.com/r/roccos-tacos-and-tequila-bar-fort-lauderdale",
				"https://www.opentable.com/r/tinta-westin-fort-lauderdale-beach-fort-lauderdale",
				"https://www.opentable.com/r/con-murphys-ocean-bar-and-grill-fort-lauderdale",
				"https://www.opentable.com/riva-marriott-harbor-beach-resort-and-spa",
				"https://www.opentable.com/r/rendezvous-ft-lauderdale-fort-lauderdale",
				"https://www.opentable.com/martis-new-river-bistro",
				"https://www.opentable.com/r/pelican-landing-fort-lauderdale",
				"https://www.opentable.com/grille-66-and-bar",
				"https://www.opentable.com/r/vegan-fine-foods-fort-lauderdale",
				"https://www.opentable.com/timpano-italian-chophouse-ft-lauderdale",
				"https://www.opentable.com/r/it-italy-fort-lauderdale",
				"https://www.opentable.com/r/el-camino-mexican-soul-food-mezcal-and-tequila-bar-fort-lauderdale",
				"https://www.opentable.com/r/bos-pub-fort-lauderdale",
				"https://www.opentable.com/r/spajuicebar-fort-lauderdale",
				"https://www.opentable.com/r/naked-crab-b-ocean-resort-fort-lauderdale",
				"https://www.opentable.com/r/here-and-now-fort-lauderdale",
				"https://www.opentable.com/r/lobby-bar-fort-lauderdale",
				"https://www.opentable.com/r/the-terrace-grill-fort-lauderdale",
				"https://www.opentable.com/r/nanou-french-bakery-fort-lauderdale",
				"https://www.opentable.com/tsukuro",
				"https://www.opentable.com/ilios-restaurant-hilton-fort-lauderdale-beach",
				"https://www.opentable.com/r/oria-osteria-and-terrazza-fort-lauderdale",
				"https://www.opentable.com/r/mojo-fort-lauderdale",
				"https://www.opentable.com/the-grill-at-calvary-chapel-of-fort-lauderdale",
				"https://www.opentable.com/r/delacaseas-cafe-lauderdale-by-the-sea",
				"https://www.opentable.com/r/sea-watch-restaurant-fort-lauderdale"
				*/
		};

	    LinkedList<String> ll = new LinkedList<String>(Arrays.asList(sa));
	    return ll;
	}
	
}
